---
language: python
services: docker

env:
    global:
        - ROLE_NAME: ansible
    matrix:
        - MOLECULE_DISTRO: centos7
        - MOLECULE_DISTRO: ubuntu1804

install:
    - pip install molecule yamllint ansible-lint docker

before_script:
    - cd ../
    - mv ansible-role-$ROLE_NAME shubhamv1436.$ROLE_NAME
    - cd shubhamv1436.$ROLE_NAME

script:
    - molecule test

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
