---

- name: Update apt caches
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present

- name: Add ansible repository
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Update apt caches
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install ansible
  apt:
    name: ansible
    state: "{{ ansible_package_state }}"
  